name: Test the action
on: [push, pull_request]
jobs:
  test:
    name: Test the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the base Docker image
        run: docker build . --file Dockerfile.base --tag jakejarvis/chrome-headless
      - uses: ./
        name: Run the app
        with:
          url: 'https://google.com'